import type { Enchantment, ItemCategory } from "./types";

/**
 * Enchantment cost multipliers follow Java Edition's rarity tiers. Each
 * enchantment has an "item" multiplier (used when the enchantment travels
 * via a non-book item) and a "book" multiplier (used when it travels via an
 * enchanted book, which is how Grovus always sources new enchantments — see
 * `optimizer.ts` for why that simplification is accurate for this tool).
 *
 * Where explicit multipliers were specified in the Grovus project brief they
 * are used verbatim. Everything else follows the standard rarity → multiplier
 * convention (Common 1, Uncommon 2, Rare 4, Very Rare 8) with the book
 * multiplier derived as `max(1, floor(itemMultiplier / 2))`, matching
 * vanilla's own halving rule. If a future Minecraft version changes these
 * values, only this file needs to change.
 */
function bookMult(itemMultiplier: number): number {
  return Math.max(1, Math.floor(itemMultiplier / 2));
}

const ALL_ARMOR: ItemCategory[] = ["helmet", "chestplate", "leggings", "boots"];
const ALL_DIGGERS: ItemCategory[] = ["pickaxe", "axe", "shovel", "hoe"];
const ALL_MELEE: ItemCategory[] = ["sword", "axe"];
const ALL_ENCHANTABLE: ItemCategory[] = [
  "sword",
  "pickaxe",
  "axe",
  "shovel",
  "hoe",
  "bow",
  "crossbow",
  "trident",
  "mace",
  "helmet",
  "chestplate",
  "leggings",
  "boots",
  "shield",
  "fishing_rod",
];

export const ENCHANTMENTS: Enchantment[] = [
  // ---- Combat ----
  {
    id: "sharpness",
    name: "Sharpness",
    shortName: "Sharp",
    maxLevel: 5,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "combat",
    compatibleItems: ALL_MELEE,
    conflictsWith: ["smite", "bane_of_arthropods"],
    description: "Increases melee damage.",
  },
  {
    id: "smite",
    name: "Smite",
    shortName: "Smite",
    maxLevel: 5,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "combat",
    compatibleItems: ALL_MELEE,
    conflictsWith: ["sharpness", "bane_of_arthropods"],
    description: "Increases damage to undead mobs.",
  },
  {
    id: "bane_of_arthropods",
    name: "Bane of Arthropods",
    shortName: "Bane",
    maxLevel: 5,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "combat",
    compatibleItems: ALL_MELEE,
    conflictsWith: ["sharpness", "smite"],
    description: "Increases damage to arthropod mobs.",
  },
  {
    id: "knockback",
    name: "Knockback",
    shortName: "KB",
    maxLevel: 2,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "combat",
    compatibleItems: ["sword"],
    conflictsWith: [],
    description: "Increases knockback dealt to mobs and players.",
  },
  {
    id: "fire_aspect",
    name: "Fire Aspect",
    shortName: "Fire",
    maxLevel: 2,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["sword"],
    conflictsWith: [],
    description: "Sets target on fire.",
  },
  {
    id: "looting",
    name: "Looting",
    shortName: "Loot",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["sword"],
    conflictsWith: [],
    description: "Increases mob loot drops.",
  },
  {
    id: "sweeping_edge",
    name: "Sweeping Edge",
    shortName: "Sweep",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["sword"],
    conflictsWith: [],
    description: "Increases sweep attack damage.",
  },

  // ---- Tools ----
  {
    id: "efficiency",
    name: "Efficiency",
    shortName: "Eff",
    maxLevel: 5,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "tools",
    compatibleItems: ALL_DIGGERS,
    conflictsWith: [],
    description: "Increases mining speed.",
  },
  {
    id: "silk_touch",
    name: "Silk Touch",
    shortName: "Silk",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "tools",
    compatibleItems: ALL_DIGGERS,
    conflictsWith: ["fortune"],
    description: "Mined blocks drop themselves.",
  },
  {
    id: "fortune",
    name: "Fortune",
    shortName: "Fort",
    maxLevel: 3,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "tools",
    compatibleItems: ALL_DIGGERS,
    conflictsWith: ["silk_touch"],
    description: "Increases block drops.",
  },

  // ---- Utility (cross-cutting) ----
  {
    id: "unbreaking",
    name: "Unbreaking",
    shortName: "Unbrk",
    maxLevel: 3,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "utility",
    compatibleItems: ALL_ENCHANTABLE,
    conflictsWith: [],
    description: "Increases durability.",
  },
  {
    id: "mending",
    name: "Mending",
    shortName: "Mend",
    maxLevel: 1,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "utility",
    compatibleItems: ALL_ENCHANTABLE,
    conflictsWith: ["infinity"],
    description: "Repairs the item using collected XP.",
  },
  {
    id: "curse_of_vanishing",
    name: "Curse of Vanishing",
    shortName: "C.Vanish",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "curses",
    compatibleItems: ALL_ENCHANTABLE,
    conflictsWith: [],
    curse: true,
    description: "Item disappears on death instead of dropping.",
  },
  {
    id: "curse_of_binding",
    name: "Curse of Binding",
    shortName: "C.Bind",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "curses",
    compatibleItems: ALL_ARMOR,
    conflictsWith: [],
    curse: true,
    description: "Item cannot be removed once worn.",
  },

  // ---- Armor ----
  {
    id: "protection",
    name: "Protection",
    shortName: "Prot",
    maxLevel: 4,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "armor",
    compatibleItems: ALL_ARMOR,
    conflictsWith: ["blast_protection", "fire_protection", "projectile_protection"],
    description: "Reduces most types of damage.",
  },
  {
    id: "blast_protection",
    name: "Blast Protection",
    shortName: "Blast",
    maxLevel: 4,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "armor",
    compatibleItems: ALL_ARMOR,
    conflictsWith: ["protection", "fire_protection", "projectile_protection"],
    description: "Reduces explosion damage and knockback.",
  },
  {
    id: "fire_protection",
    name: "Fire Protection",
    shortName: "FireP",
    maxLevel: 4,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "armor",
    compatibleItems: ALL_ARMOR,
    conflictsWith: ["protection", "blast_protection", "projectile_protection"],
    description: "Reduces fire damage and burn time.",
  },
  {
    id: "projectile_protection",
    name: "Projectile Protection",
    shortName: "ProjP",
    maxLevel: 4,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "armor",
    compatibleItems: ALL_ARMOR,
    conflictsWith: ["protection", "blast_protection", "fire_protection"],
    description: "Reduces projectile damage.",
  },
  {
    id: "thorns",
    name: "Thorns",
    shortName: "Thorns",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "armor",
    compatibleItems: ALL_ARMOR,
    conflictsWith: [],
    description: "Reflects damage onto attackers.",
  },
  {
    id: "respiration",
    name: "Respiration",
    shortName: "Resp",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "movement",
    compatibleItems: ["helmet"],
    conflictsWith: [],
    description: "Extends underwater breathing time.",
  },
  {
    id: "aqua_affinity",
    name: "Aqua Affinity",
    shortName: "Aqua",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "movement",
    compatibleItems: ["helmet"],
    conflictsWith: [],
    description: "Increases underwater mining speed.",
  },
  {
    id: "feather_falling",
    name: "Feather Falling",
    shortName: "Feather",
    maxLevel: 4,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "movement",
    compatibleItems: ["boots"],
    conflictsWith: [],
    description: "Reduces fall damage.",
  },
  {
    id: "depth_strider",
    name: "Depth Strider",
    shortName: "Depth",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "movement",
    compatibleItems: ["boots"],
    conflictsWith: ["frost_walker"],
    description: "Increases underwater movement speed.",
  },
  {
    id: "frost_walker",
    name: "Frost Walker",
    shortName: "Frost",
    maxLevel: 2,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "movement",
    compatibleItems: ["boots"],
    conflictsWith: ["depth_strider"],
    description: "Freezes water beneath your feet.",
  },
  {
    id: "soul_speed",
    name: "Soul Speed",
    shortName: "Soul",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "movement",
    compatibleItems: ["boots"],
    conflictsWith: [],
    description: "Increases speed on soul sand and soul soil.",
  },
  {
    id: "swift_sneak",
    name: "Swift Sneak",
    shortName: "Sneak",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "movement",
    compatibleItems: ["leggings"],
    conflictsWith: [],
    description: "Increases sneaking movement speed.",
  },

  // ---- Ranged ----
  {
    id: "power",
    name: "Power",
    shortName: "Power",
    maxLevel: 5,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "combat",
    compatibleItems: ["bow"],
    conflictsWith: [],
    description: "Increases arrow damage.",
  },
  {
    id: "punch",
    name: "Punch",
    shortName: "Punch",
    maxLevel: 2,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "combat",
    compatibleItems: ["bow"],
    conflictsWith: [],
    description: "Increases arrow knockback.",
  },
  {
    id: "flame",
    name: "Flame",
    shortName: "Flame",
    maxLevel: 1,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "combat",
    compatibleItems: ["bow"],
    conflictsWith: [],
    description: "Arrows set targets on fire.",
  },
  {
    id: "infinity",
    name: "Infinity",
    shortName: "Infin",
    maxLevel: 1,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "utility",
    compatibleItems: ["bow"],
    conflictsWith: ["mending"],
    description: "Shooting consumes no arrows.",
  },
  {
    id: "quick_charge",
    name: "Quick Charge",
    shortName: "QC",
    maxLevel: 3,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "combat",
    compatibleItems: ["crossbow"],
    conflictsWith: [],
    description: "Decreases crossbow reload time.",
  },
  {
    id: "multishot",
    name: "Multishot",
    shortName: "Multi",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["crossbow"],
    conflictsWith: ["piercing"],
    description: "Fires three arrows for the cost of one.",
  },
  {
    id: "piercing",
    name: "Piercing",
    shortName: "Pierce",
    maxLevel: 4,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "combat",
    compatibleItems: ["crossbow"],
    conflictsWith: ["multishot"],
    description: "Arrows pierce through multiple entities.",
  },

  // ---- Trident ----
  {
    id: "loyalty",
    name: "Loyalty",
    shortName: "Loyal",
    maxLevel: 3,
    itemMultiplier: 1,
    bookMultiplier: bookMult(1),
    category: "combat",
    compatibleItems: ["trident"],
    conflictsWith: ["riptide"],
    description: "Trident returns after being thrown.",
  },
  {
    id: "riptide",
    name: "Riptide",
    shortName: "Riptide",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["trident"],
    conflictsWith: ["loyalty", "channeling"],
    description: "Launches the player with the thrown trident in water/rain.",
  },
  {
    id: "channeling",
    name: "Channeling",
    shortName: "Chan",
    maxLevel: 1,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "combat",
    compatibleItems: ["trident"],
    conflictsWith: ["riptide"],
    description: "Summons a lightning bolt on hit during storms.",
  },
  {
    id: "impaling",
    name: "Impaling",
    shortName: "Impale",
    maxLevel: 5,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["trident"],
    conflictsWith: [],
    description: "Increases damage to aquatic mobs.",
  },

  // ---- Mace ----
  {
    id: "density",
    name: "Density",
    shortName: "Dense",
    maxLevel: 5,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "combat",
    compatibleItems: ["mace"],
    conflictsWith: [],
    description: "Increases smash-attack damage per fallen block.",
  },
  {
    id: "breach",
    name: "Breach",
    shortName: "Breach",
    maxLevel: 4,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["mace"],
    conflictsWith: [],
    description: "Reduces the effectiveness of target armor.",
  },
  {
    id: "wind_burst",
    name: "Wind Burst",
    shortName: "Wind",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: bookMult(4),
    category: "combat",
    compatibleItems: ["mace"],
    conflictsWith: [],
    description: "Launches the player upward after a smash attack.",
  },

  // ---- Fishing rod ----
  {
    id: "luck_of_the_sea",
    name: "Luck of the Sea",
    shortName: "Luck",
    maxLevel: 3,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "utility",
    compatibleItems: ["fishing_rod"],
    conflictsWith: [],
    description: "Increases chance of treasure while fishing.",
  },
  {
    id: "lure",
    name: "Lure",
    shortName: "Lure",
    maxLevel: 3,
    itemMultiplier: 2,
    bookMultiplier: bookMult(2),
    category: "utility",
    compatibleItems: ["fishing_rod"],
    conflictsWith: [],
    description: "Decreases time to get a fishing bite.",
  },
];

const BY_ID = new Map(ENCHANTMENTS.map((e) => [e.id, e]));

export function getEnchantment(id: string): Enchantment {
  const e = BY_ID.get(id);
  if (!e) throw new Error(`Unknown enchantment id: ${id}`);
  return e;
}

export function enchantmentsForItem(item: ItemCategory): Enchantment[] {
  return ENCHANTMENTS.filter((e) => e.compatibleItems.includes(item));
}

export const ENCHANT_CATEGORIES: { id: EnchantCategoryOrAll; label: string }[] = [
  { id: "all", label: "All" },
  { id: "combat", label: "Combat" },
  { id: "tools", label: "Tools" },
  { id: "armor", label: "Armor" },
  { id: "movement", label: "Movement" },
  { id: "utility", label: "Utility" },
  { id: "curses", label: "Curses" },
];

type EnchantCategoryOrAll = Enchantment["category"] | "all";
